[build]
  command = "npm run build"  # Substitua pelo comando correto, se necessário
  functions = "api/dist"     # Substitua pelo diretório de saída das funções

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
